Update Emacs config

diff --git a/scripts/bin/dotf b/scripts/bin/dotf
--- a/scripts/bin/dotf
+++ b/scripts/bin/dotf
@@ -24,7 +24,7 @@ function __restow {
 }
 
 if [[ $# -ne 1 || ! $1 =~ ^(un|re)?stow$ ]]; then
-  echo -e "${error}Usage: dotfiles ( stow | unstow | restow )${normal}" >&2
+  echo -e "${error}Usage: dotf ( stow | unstow | restow )${normal}" >&2
   exit 1
 fi
 
